mongodb:
 container_name : mongodb
 image: mongo
 ports:
  - "27017:27017"

kafka:
 image: spotify/kafka
 ports:
  - "9092:9092"
  - "2181:2181"
 environment:
  - ADVERTISED_HOST= 172.23.238.133
  - ADVERTISED_PORT= 9092

eurekaserver:
 build: ./DiscoveryRegistryService
 ports:
  - "8070:8070"

authenticationservice:
 build: ./AuthenticationService
 ports:
  - "8088:8088"

configserver:
 build: ./ConfigService/config-server
 ports:
  - "8888:8888"

studentdocker:
 build: ./StudentService
 ports:
  - "8083:9999"
 links:
  - mongodb
enginerdocker:
 build: ./EngineService
 ports:
  - "8084:9998"
 links:
  - kafka

evaluationdocker:
 build: ./evaluationManager
 ports:
  - "8085:9997"
 links:
  - kafka

evalrouterdocker:
 build : ./EvaluationRouter
 ports:
  - "8086:9996"
 links:
  - kafka

examdocker:
 build: ./ExamService
 ports:
  - "8087:8074"
 links:
  - kafka
  - mongodb

mcqevaluatordocker:
 build: ./McqEvaluatorService
 ports:
  - "8090:8022"
 links:
  - kafka
# truefalseevaldocker:
#  build: ./TrueFalseEvaluatorService
#  ports:
#   - "8092:8023"
#  links:
#   - kafka

userresultdocker:
 build: ./UserResultService
 ports:
  - "8091:9994"
 links:
  - kafka
