kafka:
  bootstrap-servers: 172.23.238.133:9092
  topic3:
    json3: Resultmanager




eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://172.23.238.225:8070/eureka/


spring:
  application:
    name: UserResultService
  kafka:
    consumer:
      group-id: ResultDisplay
server.port: 9994

